version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: rayfelmun-web
    restart: unless-stopped
    ports:
      - ${PORT}:3000
    volumes:
      - /opt/rayfelmun/web:/app
