version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: talmun-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /opt/talmun/web:/app
